#!/usr/bin/env python3

import pandas as pd 
import numpy as np 
from argparse import ArgumentParser


class ModelPerf():
    
    def __init__(self):
        pass
        
        
    def concatResults(self,paths,name):
       perfermence_df = pd.DataFrame()
       for file in paths:
          data = pd.read_csv(file)
          perfermence_df = pd.concat([perfermence_df, data], axis=0)
       perfermence_df['avg_acc']=perfermence_df.acc.mean()
       perfermence_df['avg_loss']=perfermence_df.loss.mean()
       perfermence_df.to_csv(name, index=False)
       return 
       
       


if __name__ == '__main__':
    parser = ArgumentParser(description="Pegasus Federated Learning Workflow Example")
    parser.add_argument('-f', type=str, nargs='+', help='Path to local models')
    parser.add_argument('-n', type=str, help='Output file name', default=None)
    args = parser.parse_args()
    ModelPerf().concatResults(args.f,args.n)
